Feature/pytest to product catalogue
akademiait/Dshop pull request #16
Opened 2023-08-08 09:24 UTC by jacoor

2023-08-08 09:38 UTC, RL89pl requested changes
Updated project_apps

2023-08-08 09:38 UTC, RL89pl commented on Dshop/Dshop/settings.py
> +]
```suggestion
PROJECT_APPS = [
    'apps.core',
    'apps.users',
    'apps.products_catalogue',
]
```

2023-08-13 12:52 UTC, jacoor commented
Still, conflicts needs to be fixed.

2023-08-13 12:54 UTC, jacoor commented on Dshop/Dshop/settings.py
> +]
Conflict fixed manually.

2023-08-13 21:16 UTC, merged