Feature/persistent shopping cart
akademiait/Dshop pull request #50
Opened 2023-11-02 00:48 UTC by michalkrzem

DeleteCartView added. It allows as to reduce number of items in our cart. In Template we have two option:
- plus - AddToCartView
- minus - DeleteCartView

While the template view works, I struggled with tests for DeleteCartView for a long time, but I couldn't make it work. I do not know why.

2023-11-25 00:38 UTC, michalkrzem commented
Please for review :)

2023-11-25 12:20 UTC, jacoor requested changes
small change

2023-11-25 12:20 UTC, jacoor commented on Dshop/apps/products_catalogue/models.py
> +    def is_available(self):
here: https://github.com/pymasterspl/Dshop/blob/106e33a86bd79d4b330edd2abfbf32caecb5ce76/Dshop/apps/products_catalogue/models.py#L71

2023-11-26 10:18 UTC, jacoor approved these changes

2023-11-26 13:45 UTC, merged