Voitecp task
akademiait/Dshop pull request #79
Opened 2024-02-13 06:54 UTC by VoitecP

Partially finished task,

Created Order Model, storing present data from Cart model,  Simple model for Delivery method was created

2024-02-14 19:52 UTC, jacoor requested changes
Lot's of weird changes. Please revert what was not in scope of your tasks.

2024-02-14 19:52 UTC, jacoor commented on Dshop/apps/core/api_views.py
> +# from .models import Product
What is this file? If not needed please remove.

2024-02-14 19:52 UTC, jacoor commented on Dshop/Dshop/urls.py
> +    # path('api/products/', include('apps.products_catalogue.api_urls')),
Why this change? Everyhing was under /api/XXX now this change breaks it.

2024-02-14 19:52 UTC, jacoor commented on Dshop/apps/products_catalogue/migrations/0001_initial.py
> -# Generated by Django 4.2.3 on 2023-08-06 17:58
Please revert all the migration changes and add yours as new ones. Removing those migrations will break database for everybody in the team. 
Migrations are like version control (git) for DB changes. If you delete git commits, everyone else will have issues with the repo. Same thing here.

2024-02-14 19:52 UTC, jacoor commented on Dshop/apps/products_catalogue/fixtures/fixtures_products.json
What happened here? Why changes to fixtures?

2024-02-14 19:52 UTC, jacoor commented on Dshop/apps/products_catalogue/api_urls.py
> +router.register(r'products', ProductViewSet, basename='products-api')
Why changing the url? The idea was that products list is on home page. That was not part of your task, please revert. 
Also, please review all the changes and stick to what was in the task: Order and Delivery method. Please revert everything else.

2024-02-14 19:54 UTC, jacoor commented
@VoitecP pease also fix conflicts. I believe that most of the conflicts might be gone once you revert the changes that should not be here.

2024-02-14 19:57 UTC, jacoor commented
One more remark is for the descripion
- the title of the PR should mention what is the PR about
- the commits should be described by what the change is, not like "partially completed task". Please check here: https://github.com/pymasterspl/Dshop/pull/69 - every commit is described with what it does.

2024-02-15 17:48 UTC, VoitecP commented
Pushed new branch, with correct name,   removed conflicts. This branch propably need's to be delete.

2024-04-13 11:15 UTC, closed without merging

2024-04-13 11:15 UTC, jacoor commented
deleted