Tests of products api filters and sorting
akademiait/Dshop pull request #94
Opened 2024-03-26 13:38 UTC by yanazPL

Fixed small bug in availability filtter.

Made products fixture return list - for ease of testing.

In this fixture created_at has been ignored (can't change auto_now_add field)
`created_at = models.DateTimeField(auto_now_add=True)`

Now tests make use of default created_at

Added two small fixtures.

I have created testes for every filter and ordering.

2024-04-08 08:55 UTC, jacoor requested changes
Looks good, however those copy and paste things has to be removed.

2024-04-08 08:55 UTC, jacoor commented on Dshop/apps/products_catalogue/tests/test_api_product_filters.py
> +def named_products(products):
oh come on, please make it a loop.

2024-04-08 08:55 UTC, jacoor commented on Dshop/apps/products_catalogue/tests/test_api_product_filters.py
> +    print(response.data)
remove print

2024-04-08 08:55 UTC, jacoor commented on Dshop/apps/products_catalogue/tests/test_api_product_filters.py
> +    for value, prod in enumerate(products_data, start=1):
What about 0 record?

2024-04-08 08:55 UTC, jacoor commented on Dshop/apps/products_catalogue/tests/test_api_product_filters.py
> +    products[0].availability = 1
please move it into loop.

2024-04-09 11:50 UTC, yanazPL commented on Dshop/apps/products_catalogue/tests/test_api_product_filters.py
> +    for value, prod in enumerate(products_data, start=1):
record 0 is there, but it's price is 1

2024-04-09 11:50 UTC, yanazPL commented on Dshop/apps/products_catalogue/tests/test_api_product_filters.py
> +    print(response.data)
done

2024-04-09 11:51 UTC, yanazPL commented on Dshop/apps/products_catalogue/tests/test_api_product_filters.py
> +def named_products(products):
done

2024-04-09 12:20 UTC, jacoor approved these changes

2024-04-09 12:20 UTC, merged